### PR TITLE
Export pfx from secret as tls

### PR DESCRIPTION
**Pull request by svjo**
Hi,

this PR helps using certificates stored as Base64 PFX inside a Azure Key Vault secret. These secrets are generate for example by Azure's App Service Certificate service. As this certificate isn't stored as Azure Key Vault Certificate it currently cannot be synced with akv2k8s to a Kubernetes secret.

### CODE REVIEW

**Comment by wimi** [comment]
Hello,

we believe this PR will also solve this issue: https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/70

**Comment by 181192** [comment]
Thank you very much @svjo, great work! :relaxed:

**Comment by 181192** [comment]
Released controller with version `controller-1.3.0-beta.1`

```
docker pull spvest/azure-keyvault-controller:1.3.0-beta.1
```

Would you guys @svjo and @wimi help with verify that it solves this PR and #70 ? :relaxed:

**Comment by svjo** [comment]
@181192 Already verified that these changes work in a real world scenario. Seems we have the same setup as described in #70. The certificate is used by our nginx controller. Important step here was that it is also using the `ensureserverfirst` chain order. 

I can check against the beta version that you provided if you want but as the code is the same I'm expecting the same successful result.

**Comment by 181192** [comment]
Allright thanks @svjo! Correct, working with Ingress Nginx Controller tls secrets needs to have the server certificate first for Nginx to pick it up

**Pull request merged**
