### PR TITLE
Allow to run in specific namespace only

### PR DESCRIPTION
**Pull request by laozc**
Listen to informer changes in a specific namespace to run multiple instances within a cluster without inferring each other.

### CODE REVIEW

**Comment by torresdal** [comment]
Thanks for you contribution @laozc - this is a good start. In order to add this, we would need to update Helm charts and document this in `/docs`. Could you look into that as well?

**Comment by laozc** [comment]
Hi, would you mind reviewing and approving this PR? Thanks.

**Comment by 181192** [comment]
Hello @laozc, sorry for the late reply. 
I've reviewed your changes and have a proposal.

Adding a new boolean CLI argument `watch-all-namespaces` and setting a environment variable called `RUNTIME_NAMESPACE` that is being set in the deployment using the Downward API for setting the namespace.


Changes in `main.go`

```go
func init() {
  <...>
  flag.BoolVar(&watchAllNamespaces, "watch-all-namespaces", true,
		"Watch for custom resources in all namespaces, if set to false it will only watch the runtime namespace.")
}
```

Setting watchNamespace to `""` is equal to all namespaces.
```go
func main() {
  <...>
  watchNamespace := ""
  if !watchAllNamespaces {
    watchNamespace = os.Getenv("RUNTIME_NAMESPACE")
  }

  kubeInformerFactory := kubeinformers.NewSharedInformerFactoryWithOptions(kubeClient, time.Second*30, kubeinformers.WithNamespace(watchNamespace))
  azureKeyVaultSecretInformerFactory := informers.NewSharedInformerFactoryWithOptions(azureKeyVaultSecretClient, time.Second*30, informers.WithNamespace(watchNamespace))
}
``` 

In the Kubernetes deployment following need to be added:
```yaml
<...>
env:
  - name: RUNTIME_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
args:
  - --watch-all-namespaces
<...>
```
Single/release namespace:
```yaml
<...>
env:
  - name: RUNTIME_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
args:
  - --watch-all-namespaces=false
<...>
```

Using the Downward API will result in controller always apply to RBAC when running in single namespace. 
Some additional changes to RBAC in the Helm chart should also be reviewed to ensure namespace scope.

**Review by 181192 — APPROVED** [review]

**Comment by 181192** [comment]
Thank you very much @laozc :relaxed:

**Comment by laozc** [comment]
Sure. Glad to help.

**Pull request merged**
