### PR TITLE
Add nonroot user permission

### PR DESCRIPTION
**Pull request by abhilashjoseph**
* rem restricted del sticky bit

Co-authored-by: Pavel <bambriy@users.noreply.github.com>

### CODE REVIEW

**Comment by torresdal** [comment]
@ abhilashjoseph Thanks for your pull request. Could you please explain a bit more about this change and why these settings specifically? It’s not that we don’t understand the change, just to document the intent and what you accomplish with it.

**Comment by abhilashjoseph** [comment]
> @abhilashjoseph Thanks for your pull request. Could you please explain a bit more about this change and why these settings specifically? It’s not that we don’t understand the change, just to document the intent and what you accomplish with it.

sure @torresdal, Thanks for looking at it. We actually run our images with a non root user, due to this, the delete steps fail, because the delete is done on the contents inside a folder in the root of the file system. The reason for that was that the root folder (/azure-keyvault) is created by a root user and needs all the permissions including the -t to be set on the folder to be able to be removed during deletesensitive files step and the +x permission to run the executable.

**Comment by abhilashjoseph** [comment]
@torresdal , Also have seen that the delete sensitive files have been commented out recently, we had the delete work without any issue with a change in the order of execution, i'll send out a PR for that as well, but may I know what exactly was the issue with the container delete and start comment that was mentioned on the commit comment.

**Comment by torresdal** [comment]
@abhilashjoseph Thanks for the explanation. Based on the logic at the time, your PR made perfect sense. The reason we commented out the deletion of sensitive files is covered in #42 and also explained in the [latest release](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/releases/tag/1.0.2). Short version is that if a container fails and the pod needs to restart the container to recover, it will fail. Reason being it simply needs the deleted files to recover.

This is of course unacceptable, so we started to redesign how the injector uses default authentication. As of today a new version is in Beta and currently being tested, where we avoid the most sensitive file all together, which was the `azure.json` containing the cluster credentials. Instead we have the webhook provide a auth endpoint to the injector (protected by a client cert), where a oauth token will be issued instead of passing the cluster credentials, thereby fixing the issue and preventing exposing these credentials inside every pod.

**Comment by abhilashjoseph** [comment]
> @abhilashjoseph Thanks for the explanation. Based on the logic at the time, your PR made perfect sense. The reason we commented out the deletion of sensitive files is covered in #42 and also explained in the [latest release](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/releases/tag/1.0.2). Short version is that if a container fails and the pod needs to restart the container to recover, it will fail. Reason being it simply needs the deleted files to recover.
> 
> This is of course unacceptable, so we started to redesign how the injector uses default authentication. As of today a new version is in Beta and currently being tested, where we avoid the most sensitive file all together, which was the `azure.json` containing the cluster credentials. Instead we have the webhook provide a auth endpoint to the injector (protected by a client cert), where a oauth token will be issued instead of passing the cluster credentials, thereby fixing the issue and preventing exposing these credentials inside every pod.

Thanks @torresdal, thanks for the detailed explanation!!

**Pull request closed without merging**
