### PR TITLE
Custom resync periods

### PR DESCRIPTION
**Pull request by wimi**
This PR solves issue https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/issues/327

PR provides a global way of reconfiguring resync periods for k8s and Azure Key Vault informers from standard 30s.

### CODE REVIEW

**Comment by PsychoNineSix** [comment]
@torresdal @181192 Is it possible to get this merged?
If time is an issue maybe the project needs more maintainers?

**Comment by YvesZelros** [comment]
@181192 @toreandreb It's possible to review this pr ?

**Review by 181192 — APPROVED** [review]
Thank you @wimi , I'm sorry I haven't followed this one up.

**Comment by dimuskin** [comment]
please update documentation (https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/akv2k8s). 
currently there are two parameters:

**azureKeyVaultResyncPeriod
kubeResyncPeriod**

with same description (_Resync periods for the controller in seconds_)

**Pull request merged**
